name: Go Unit Test

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test with Coverage
        run: go test -v -coverprofile=coverage_dev.txt -covermode=atomic ./...

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage_dev.txt
          token: ${{ secrets.CODECOV_TOKEN }}