name: Go Unit Test 101 

on:
  push:
    branches:
      - 'feature/*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Get Previous Commit
        id: previous-commit
        run: |
          echo "::set-output name=commit::$(curl -s -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }} --header 'Accept: application/vnd.github.v3+json' | jq -r '.parents[0].sha')"

      - name: Get Changed Files
        id: changed-files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ steps.previous-commit.outputs.commit }})"

      - name: Display Changed Files
        run: |
          echo "Changed Files: ${{ steps.changed-files.outputs.files }}"

      - name: Run Tests
        run: |
          go test ${{ steps.changed-files.outputs.files }}